### ISSUE TITLE
`OXIDE_HOST` is more picky than `oxide auth login --host`

### ISSUE THREAD

**Issue by iliana** [oxidecomputer/oxide.rs#657] opened 2024-05-01 17:31 UTC
### Component

- [X] CLI
- [ ] SDK
- [ ] Something else
- [ ] Not sure

### What was the expected behaviour

`oxide auth login --host https://oxide.sys.rack2.eng.oxide.computer`

followed by

`OXIDE_HOST=https://oxide.sys.rack2.eng.oxide.computer oxide disk import ...`

should work.

### What is the current behaviour and what actions did you take to get there

The URL is canonicalized and stored in `~/.config/oxide/hosts.toml` as `"https://oxide.sys.rack2.eng.oxide.computer/"` (note the trailing slash). When setting `OXIDE_HOST` to include the trailing slash, the command works.

### CLI or SDK version

Oxide CLI 0.4.0+20240327.0 Built from commit: 413a2f799ab908007178a1ea8bd582889e44351f Oxide API: 20240327.0

### Operating system

macOS

**Comment by david-crespo** [comment] 2024-05-01 17:43
Semi-dupe of this: https://github.com/oxidecomputer/oxide.rs/issues/163#issuecomment-1889716777

**Comment by ahl** [comment] 2024-07-17 21:23
I think this is more or less addressed by #727

**Closed as completed by ahl** 2024-07-17 21:23 UTC
